# This is a basic workflow that is manually triggered

name: Attempt to test the full test suite
on: pull_request

jobs:
  attempt:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ${{ github.repository }} @ ${{ github.ref }}
      uses: actions/checkout@v2
    - name: Install NodeJs
      uses: actions/setup-node@v1
      with: 
        node-version: 16.x
    - name: run test suite
      run: node run
